# Site settings
name: Today I Learned
title: Developer
email: dushyant.rao@gmail.com
description: "BITSian, Eagle, Coder, Aspiring Chef, Sailor, Telugu + Sindhi, Foodie"
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalinks: pretty
