# Site settings
name: Dushyant Rao
title: Developer
email: dushyant.rao@gmail.com
description: "BITSian, Eagle, Coder, Aspiring Chef, Sailor, Telugu + Sindhi, Foodie"
baseurl: ""
url: "http://dushyantrao.github.io"

# Build settings
markdown: kramdown
permalinks: pretty
